---

- name: Add crafter user/group
  user:
    name: crafter

- name: Fetch and unpack Crafter CMS archive
  unarchive:
    src: /vagrant/files/crafter-cms-authoring-3.1.3.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/crafter/bin/startup.sh
    owner: crafter
    group: crafter

- name: Create dir /opt/crafter/data/repos/sites
  file:
    path: /opt/crafter/data/repos/sites
    state: directory
    owner: crafter
    group: crafter
    mode: 0755

- name: Update studio-config-override.yaml
  template:
    src: studio-config-override.yaml.j2
    dest: /opt/crafter/bin/apache-tomcat/shared/classes/crafter/studio/extension/studio-config-override.yaml

- name: Update crafter-setenv.sh
  template:
    src: crafter-setenv.sh.j2
    dest: /opt/crafter/bin/crafter-setenv.sh

- name: Start Crafter CMS
  command: nohup bin/startup.sh
  args:
    chdir: /opt/crafter
  environment:
    JAVA_HOME: "/usr/java/default"
  become: yes
  become_user: crafter

- name: Wait for Studio port
  wait_for:
    port: 8080
