---

- hosts: all
  gather_facts: yes
  become: yes
  any_errors_fatal: yes
  roles:
    - common
    - mariadb
    - haproxy

- hosts: all
  gather_facts: yes
  become: yes
  any_errors_fatal: yes
  serial: 1
  roles:
    - craftercms

